phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - npm run build
      # copy appspec.yml and scripts/ into build folder
      - cp -r appspec.yml scripts build/
artifacts:
  files:
    - '**/*'
  base-directory: build
